import type { Metadata } from "next"

import "./globals.css"

import { Montserrat_Alternates } from "next/font/google"

const montserratAlternates = Montserrat_Alternates({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${montserratAlternates.className} antialiased`}>
        {children}
      </body>
    </html>
  )
}
