import type { Metadata } from "next"

import "./globals.css"

import { Kodchasan, Qwigley } from "next/font/google"

const kodchasan = Kodchasan({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-kodchasan",
})

const qwigley = Qwigley({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-qwigley",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${qwigley.variable} ${kodchasan.variable}`}>
      <body className={`${kodchasan.className} min-h-screen antialiased`}>
        {children}
      </body>
    </html>
  )
}
